name: Algorithm Tests - JS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ dev ]

defaults:
  run:
    working-directory: javascript

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        # node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn run build --if-present
    - run: yarn test-dev 